<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'spriebsch\\oop\\dependencies\\abstractbasecontroller' => '/AbstractBaseController.php',
                'spriebsch\\oop\\dependencies\\controllerinterface' => '/ControllerInterface.php',
                'spriebsch\\oop\\dependencies\\heavycontroller' => '/HeavyController.php',
                'spriebsch\\oop\\dependencies\\someservice' => '/SomeService.php',
                'spriebsch\\oop\\dependencies\\staticservice' => '/StaticService.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
