<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'burger' => '/Burger.php',
                'meatbasedburger' => '/MeatBasedBurger.php',
                'meatbasedpatty' => '/MeatBasedPatty.php',
                'patty' => '/Patty.php',
                'plantbasedburger' => '/PlantBasedBurger.php',
                'plantbasedpatty' => '/PlantBasedPatty.php',
                'restaurant' => '/Restaurant.php',
                'restaurant1' => '/Restaurant1.php',
                'restaurant2' => '/Restaurant2.php',
                'sauce' => '/Sauce.php',
                'secretsauce' => '/SecretSauce.php',
                'secretsaucefactory' => '/SecretSauceFactory.php',
                'specialsauce' => '/SpecialSauce.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
